### ISSUE TITLE
Convert auto-tank to jtin

### ISSUE THREAD

**Issue by zteater** [jedimud/tintin-data#118]

**Comment by nickburton** [comment]
Hey @zteater it’s Baelen. What does ‘reverse’ do?

**Comment by zteater** [comment]
@nickburton it reverses the colors of the foreground and background in the terminal.
<img width="546" alt="Screen Shot 2021-04-24 at 10 23 38 AM" src="https://user-images.githubusercontent.com/8954363/115962021-4bbcd800-a4e7-11eb-8af5-ec4eafc515a3.png">
